version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install jq
          command: apt-get update && apt-get install -y jq

      - run:
          name: Download claat
          command: ./.circleci/download_claat.sh

      - run:
          name: Publish codelab
          command: ./codelab_gen.sh
