name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install jq
      run: sudo apt-get -y update && sudo apt-get -y install jq
    - name: Deploy
      run: ./script/deploy.sh
